[features]
seeds = false
skip-lint = false

[programs.localnet]
oraculo = "3yiUbupcQVVfU8XMd8594GEWbSjVHBXrHzWEcu9GqfZ2"
governance_token = "BJBEwqCTA8kPehiqV7jzSRKonbhGVDfWSuPFSvw7kRoN"

[programs.devnet]
oraculo = "3yiUbupcQVVfU8XMd8594GEWbSjVHBXrHzWEcu9GqfZ2"
governance_token = "BJBEwqCTA8kPehiqV7jzSRKonbhGVDfWSuPFSvw7kRoN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
